/*
 * File: app/controller/UserEditingController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GenPres.controller.UserEditingController', {
    extend: 'Ext.app.Controller',

    models: [
        'UserModel'
    ],
    stores: [
        'UserStore'
    ],
    views: [
        'UserGrid'
    ],
    
    refs: [
        {
            ref: 'userGrid',
            selector: 'grid'
        }
    ],

    window:null,

    init: function() {
        this.control({
            'button[action=new]': {
                click: this.newUser
            },
            'button[action=cancel]': {
                click: this.closeWindow
            },
            'button[action=edit]': {
                click: this.saveUsers
            },
            'grid': {
                canceledit: this.cancelEdit,
                edit:this.commitRecord,
            }
        });
    },
    
    newUser: function() {
        
        var rowEditing = this.getUserGrid().plugins[0];
        
        rowEditing.cancelEdit();

        // Create a model instance
        var r = Ext.create('GenPres.model.UserModel', {
            username: '',
            password: ''
        });

        this.getUserGrid().store.insert(0, r);
        rowEditing.startEdit(0, 0);
        
    },
    
    saveUsers: function() {
        var store = this.getUserGrid().store;
    },
    
    cancelEdit: function (editor, e, opts) {    
        if (e.record.data.username == '' || e.record.data.password == '') {
            e.store.remove(e.record);
        }   
    },
    
    commitRecord: function (editor, e) {
        Management.SaveUser(e.record.data, function(result) {
           // e.store.reload();
        });
    },
    
    showWindow: function(){
        this.window = Ext.create('Ext.window.Window', {
            title: 'Edit User',
            height: 400,
            width: 400,
            layout: 'fit',
            items: Ext.create('GenPres.view.UserForm')
        }).show();
    },
    
    closeWindow:function() {
        this.window.close();
    }
});
